# Generated by Django 3.1.7 on 2021-04-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skills',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
