# Generated by Django 3.1.7 on 2021-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210426_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='skill',
        ),
        migrations.AddField(
            model_name='employee',
            name='skill',
            field=models.ManyToManyField(to='employee.skills'),
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill',
        ),
        migrations.AddField(
            model_name='skills',
            name='skill',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
