# Generated by Django 3.1.7 on 2021-04-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_skills_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='skill',
        ),
        migrations.AddField(
            model_name='employee',
            name='skill',
            field=models.ManyToManyField(to='employee.skills'),
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill',
        ),
        migrations.AddField(
            model_name='skills',
            name='skill',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
