# Generated by Django 3.1.7 on 2021-04-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210420_2025'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
        migrations.AlterModelTable(
            name='skills',
            table=None,
        ),
        migrations.AlterModelTable(
            name='team',
            table=None,
        ),
    ]
